# Volume Longhorn pour /config : 2 répliques (une sur nas1, une sur nas2).
# (Le namespace "media" existe déjà, créé pour radarr.)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: media
spec:
  storageClassName: longhorn
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
