# Base MariaDB (2 répliques Longhorn) et /config de l'application
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speedtest-db
  namespace: media
spec:
  storageClassName: longhorn
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speedtest-tracker-config
  namespace: media
spec:
  storageClassName: longhorn
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
