# Config de jackett : 2 répliques Longhorn (nas1 + nas2)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-config
  namespace: media
spec:
  storageClassName: longhorn
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
