# Config + base SQLite de seer : 2 répliques Longhorn (nas1 + nas2)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seer-config
  namespace: media
spec:
  storageClassName: longhorn
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
